import { useState } from 'react';
import AuthForm from './AuthForm';
import { useAuth } from '../../context/AuthContext';
import { AnimatePresence, motion } from 'framer-motion';
import { Eye, EyeOff, LockKeyhole, Mail, UserRound } from 'lucide-react';

export default function Register({ onNavigate }) {
  const { login } = useAuth(); const [form, setForm] = useState({ displayName: '', email: '', password: '', confirm: '' }); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false); const [visible,setVisible]=useState(false);
  const submit = (e) => { e.preventDefault(); setError(''); setNotice(''); setBusy(true); login({ email: form.email, displayName: form.displayName || 'ผู้ใช้ทดสอบ' }); window.setTimeout(() => { setBusy(false); onNavigate('/'); }, 250); };
  const field={hidden:{opacity:0,y:10},show:{opacity:1,y:0}}; const change=(name)=>e=>setForm({...form,[name]:e.target.value}); const password=(name,label)=><motion.label variants={field}>{label}<span className="auth-input"><LockKeyhole size={18}/><input type={visible?'text':'password'} value={form[name]} onChange={change(name)} placeholder="••••••••" />{name==='password'&&<button type="button" className="auth-eye" aria-label="แสดงหรือซ่อนรหัสผ่าน" onClick={()=>setVisible(!visible)}>{visible?<EyeOff size={18}/>:<Eye size={18}/>}</button>}</span></motion.label>;
  return <AuthForm title="สมัครสมาชิก" subtitle="สร้างบัญชีเพื่อเก็บข้อมูลสวนของคุณ"><motion.form className="auth-form" onSubmit={submit} initial="hidden" animate="show" transition={{staggerChildren:.07}}><motion.label variants={field}>ชื่อที่แสดง<span className="auth-input"><UserRound size={18}/><input value={form.displayName} onChange={change('displayName')} placeholder="ชื่อของคุณ" /></span></motion.label><motion.label variants={field}>อีเมล<span className="auth-input"><Mail size={18}/><input type="email" value={form.email} onChange={change('email')} placeholder="name@example.com" /></span></motion.label>{password('password','รหัสผ่าน')}{password('confirm','ยืนยันรหัสผ่าน')}<AnimatePresence>{error && <motion.p className="auth-error" initial={{opacity:0,y:-8}} animate={{opacity:1,y:0,x:[0,-6,6,-4,4,0]}} exit={{opacity:0}}>{error}</motion.p>}{notice && <motion.p className="auth-notice" initial={{opacity:0,y:-8}} animate={{opacity:1,y:0}}>{notice}</motion.p>}</AnimatePresence><motion.button variants={field} whileHover={{scale:1.02}} whileTap={{scale:.98}} disabled={busy}>{busy ? <span className="auth-dots">กำลังสมัคร<i/><i/><i/></span> : 'สมัครสมาชิก'}</motion.button><motion.p variants={field}>มีบัญชีแล้ว? <a onClick={() => onNavigate('/login')}>เข้าสู่ระบบ</a></motion.p></motion.form></AuthForm>;
}
