import { motion } from 'framer-motion';
import './plant-info.css';

const plants = [
  { icon: '🌶️', name: 'พริก', sun: 'แดดจัด 6–8 ชม.', water: 'รดน้ำทุกวัน', harvest: '70–90 วัน', soil: 'ดินร่วน ระบายน้ำดี', issue: 'เพลี้ยและรากเน่า', tip: 'ใช้ดินร่วนระบายน้ำดีและอย่าให้น้ำขัง' },
  { icon: '🌿', name: 'โหระพา', sun: 'แดดครึ่งวัน', water: 'รดน้ำสม่ำเสมอ', harvest: '35–45 วัน', soil: 'ดินร่วนชุ่มน้ำ', issue: 'ใบเหลืองจากน้ำขัง', tip: 'เด็ดปลายยอดบ่อย ๆ เพื่อให้แตกกิ่งพุ่มสวย' },
  { icon: '🍃', name: 'กะเพรา', sun: 'แดดจัด 6 ชม.', water: 'รดน้ำเมื่อดินแห้ง', harvest: '30–40 วัน', soil: 'ดินโปร่ง มีปุ๋ยหมัก', issue: 'เพลี้ยอ่อนและราใบจุด', tip: 'ตัดช่อดอกออกเพื่อช่วยให้ใบดก' },
  { icon: '🍅', name: 'มะเขือเทศ', sun: 'แดด 6–8 ชั่วโมง', water: 'รดน้ำที่โคนต้น', harvest: '80–100 วัน', soil: 'ดินร่วน pH 6–6.8', issue: 'ใบไหม้และแมลงหวี่ขาว', tip: 'ค้ำต้นเมื่อต้นสูงและหลีกเลี่ยงใบเปียก' },
  { icon: '🥬', name: 'ผักกาดหอม', sun: 'แสงรำไร', water: 'ดินชื้นเสมอ', harvest: '40–55 วัน', soil: 'ดินร่วนซุย', issue: 'ทากและใบไหม้', tip: 'หลีกเลี่ยงแดดแรงจัดเพราะใบอาจขม' },
];

export default function PlantInfoPage({ onBack, onStart }) {
  return <motion.main className="pi-root" initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: .4 }}><div className="pi-wrap"><motion.button whileHover={{ x: -4 }} whileTap={{ scale: .97 }} className="pi-back" onClick={onBack}>← กลับหน้าแรก</motion.button><motion.header initial={{ y: -18, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ delay: .08 }}><p>PLANT LIBRARY</p><h1>ข้อมูลพืชทั่วไป</h1><span>เริ่มต้นรู้จักพืชผักสวนครัวที่ปลูกง่าย พร้อมเคล็ดลับดูแลเบื้องต้น</span></motion.header><motion.section className="pi-intro" initial={{ scale: .97, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} transition={{ delay: .13 }}><motion.span animate={{ rotate: [0, 8, -8, 0] }} transition={{ duration: 3, repeat: Infinity }}>🌱</motion.span><div><b>เลือกพืชที่เหมาะกับพื้นที่ของคุณ</b><p>เริ่มจากพืชที่ได้รับแสงตามมี และดูแลน้ำให้พอดีก่อน แล้วค่อยเพิ่มชนิดพืชในสวน</p></div><small>5 ชนิดแนะนำ</small></motion.section><div className="pi-grid">{plants.map((plant, index) => <motion.article className="pi-card" key={plant.name} initial={{ y: 22, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ delay: .12 + index * .07 }} whileHover={{ y: -7, boxShadow: '0 20px 35px -24px rgba(35,105,68,.45)' }}><motion.div className="pi-card-head" whileHover={{ x: 3 }}><motion.div className="pi-icon" whileHover={{ rotate: [0, -10, 10, 0], scale: 1.15 }}>{plant.icon}</motion.div><div><h2>{plant.name}</h2><span>เก็บเกี่ยวได้ใน {plant.harvest}</span></div></motion.div><div className="pi-facts"><p><b>☀️ แสง</b>{plant.sun}</p><p><b>💧 น้ำ</b>{plant.water}</p><p><b>🪴 ดิน</b>{plant.soil}</p><p><b>⚠️ ระวัง</b>{plant.issue}</p></div><p className="pi-tip"><b>เคล็ดลับ:</b> {plant.tip}</p></motion.article>)}</div><section className="pi-guide"><h2>หลักง่าย ๆ สำหรับมือใหม่</h2><div><article><span>1</span><b>เริ่มจากแสง</b><p>สังเกตว่าพื้นที่ของคุณได้แดดช่วงไหนก่อนเลือกพืช</p></article><article><span>2</span><b>อย่ารดน้ำเกิน</b><p>เช็กหน้าดินเสมอ น้ำมากเกินไปทำให้รากเน่าได้</p></article><article><span>3</span><b>หมั่นสังเกตใบ</b><p>ใบคือสัญญาณแรกของแมลง โรค หรือปัญหาธาตุอาหาร</p></article></div></section><motion.section className="pi-cta" whileHover={{ scale: 1.01 }}><div><p>พร้อมเริ่มปลูกแล้วหรือยัง?</p><h2>บันทึกพืชต้นแรกของคุณได้เลย</h2></div><motion.button whileHover={{ scale: 1.06 }} whileTap={{ scale: .97 }} onClick={onStart}>เพิ่มพืชของฉัน →</motion.button></motion.section></div></motion.main>;
}
